# version: '3.8'

# services:
#   # 1. Hamari FastAPI Service
#   api:
#     build: .
#     container_name: news-api
#     restart: always  # Agar crash ho toh Docker khud dobara start karega
#     ports:
#       - "8000:8000"
#     # env_file se saare variables uthayega
#     env_file:
#       - .env
#     environment:
#       # Inko yahan likhne se Docker force karta hai ke .env se values uthai jayein
#       - DATABASE_URL=${DATABASE_URL}
#       - GROQ_API_KEY=${GROQ_API_KEY}
#       - PYTHONUNBUFFERED=1
#     depends_on:
#       db:
#         condition: service_healthy # Sirf tab start hoga jab DB ready ho

#   # 2. Hamari PostgreSQL Database Service
#   db:
#     image: postgres:15
#     container_name: news-db
#     environment:
#       - POSTGRES_USER=myuser
#       - POSTGRES_PASSWORD=mypassword
#       - POSTGRES_DB=fakenewsdb
#     ports:
#       - "5433:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U myuser -d fakenewsdb"]
#       interval: 5s
#       timeout: 5s
#       retries: 5
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:




version: '3.8'

services:
  api:
    build: .
    container_name: news-api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - backend_network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: news-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: